[logging]
##日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
level = INFO
log_dir = ./logs

[database]
host = localhost
port = 3306
username = root
password = qq852631192
database = baostock_api_market_data

[webserver]
host = 127.0.0.1
port = 8080

[backtradedate]
start_date = 2020-01-01
end_date = 2025-12-29
frequency = d

[questdb]
## QuestDB配置（时序数据库）
host = localhost
port = 9000
username = 
password = 
